// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHI6hJceXh7E8O5GDGDAjxjtJqJURx-c',
    appId: '1:984725875220:web:5eae17068de95945659501',
    messagingSenderId: '984725875220',
    projectId: 'checkbike-331c8',
    authDomain: 'checkbike-331c8.firebaseapp.com',
    storageBucket: 'checkbike-331c8.appspot.com',
    measurementId: 'G-LMJ26Q6LMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANAO7buRASbKC_cD9ZfNXQigD30G2Bpo',
    appId: '1:984725875220:android:83ab06071aa6e11c659501',
    messagingSenderId: '984725875220',
    projectId: 'checkbike-331c8',
    storageBucket: 'checkbike-331c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeySa1qpLSAf-r66yU4xJD4iZfDJ1IYjI',
    appId: '1:984725875220:ios:4d613ae4ba20fe37659501',
    messagingSenderId: '984725875220',
    projectId: 'checkbike-331c8',
    storageBucket: 'checkbike-331c8.appspot.com',
    iosBundleId: 'com.example.checkBike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeySa1qpLSAf-r66yU4xJD4iZfDJ1IYjI',
    appId: '1:984725875220:ios:4d613ae4ba20fe37659501',
    messagingSenderId: '984725875220',
    projectId: 'checkbike-331c8',
    storageBucket: 'checkbike-331c8.appspot.com',
    iosBundleId: 'com.example.checkBike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHI6hJceXh7E8O5GDGDAjxjtJqJURx-c',
    appId: '1:984725875220:web:fa5dc79e0e2721d4659501',
    messagingSenderId: '984725875220',
    projectId: 'checkbike-331c8',
    authDomain: 'checkbike-331c8.firebaseapp.com',
    storageBucket: 'checkbike-331c8.appspot.com',
    measurementId: 'G-GE8R06XMWJ',
  );
}
